In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

C:\Users\ManiShankar\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [31]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [6]:
data = pd.read_csv("C:/Users/ManiShankar/Documents/LetsUpgrade/AI_ML/Materials/Datasets/DecisionTree train.csv")

In [7]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [8]:
data.tail()

PassengerId  Survived  Pclass                                      Name  \
884          887         0       2                     Montvila, Rev. Juozas   
885          888         1       1              Graham, Miss. Margaret Edith   
886          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
887          890         1       1                     Behr, Mr. Karl Howell   
888          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
884    male  27.0      0      0      211536  13.00   NaN        S  
885  female  19.0      0      0      112053  30.00   B42        S  
886  female  45.0      1      2  W./C. 6607  23.45   NaN        S  
887    male  26.0      0      0      111369  30.00  C148        C  
888    male  32.0      0      0      370376   7.75   NaN        Q

In [9]:
data.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
dtype: int64

In [10]:
len(data)

889

1. Since most of the entries of cabin are null, we drop it
2. Name does not have any significance so drop it

In [13]:
data.drop(['Name','Cabin'], axis = 1, inplace = True)

In [14]:
data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Embarked'],
      dtype='object')

In [15]:
data.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Embarked        object
dtype: object

In [16]:
le = LabelEncoder()

In [22]:
data['Sex'] = le.fit_transform(data.Sex)

In [23]:
data['Ticket'] = le.fit_transform(data.Ticket)

In [24]:
data['Embarked'] = le.fit_transform(data.Embarked)

In [25]:
data = data.astype(np.int64)

In [26]:
data.dtypes

PassengerId    int64
Survived       int64
Pclass         int64
Sex            int64
Age            int64
SibSp          int64
Parch          int64
Ticket         int64
Fare           int64
Embarked       int64
dtype: object

In [58]:
def NaiveBayes(x,y):
    x_train,x_test,y_train,y_test = train_test_split(x, y, test_size = 0.3, random_state = 0)
    clf = GaussianNB()
    clf.fit(x_train,y_train)
    y_pred = clf.predict(x_test)
    print("Accuracy_score:",accuracy_score(y_test, y_pred))
    print("Confusion Matrix:\n",confusion_matrix(y_test, y_pred))

# Model 1 Survived Vs Remaining DV

In [59]:
y = data['Survived']

In [60]:
x = data[['PassengerId', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Embarked']]

In [61]:
print("Survived Vs Remaining DV")
NaiveBayes(x,y)

Survived Vs Remaining DV
Accuracy_score: 0.7602996254681648
Confusion Matrix:
 [[125  32]
 [ 32  78]]


In [74]:
models = ['Pclass','Sex','SibSp','Parch','Embarked']

In [82]:
for col in models :
    y = data[col]
    x = data.drop(col,axis=1)
    print("")
    print(col,"Vs Remaining Dv")
    NaiveBayes(x,y)


Pclass Vs Remaining Dv
Accuracy_score: 0.7528089887640449
Confusion Matrix:
 [[ 52  14   4]
 [  5  33  11]
 [  6  26 116]]

Sex Vs Remaining Dv
Accuracy_score: 0.7153558052434457
Confusion Matrix:
 [[ 52  46]
 [ 30 139]]

SibSp Vs Remaining Dv
Accuracy_score: 0.6554307116104869
Confusion Matrix:
 [[147  16   2  16   1   0   0]
 [ 34  20   0  11   0   0   0]
 [  6   1   1   0   0   0   0]
 [  2   0   0   2   3   0   0]
 [  0   0   0   0   2   0   0]
 [  0   0   0   0   0   1   0]
 [  0   0   0   0   0   0   2]]

Parch Vs Remaining Dv
Accuracy_score: 0.6554307116104869
Confusion Matrix:
 [[163   9   2  11  13]
 [ 20   5   3   8   4]
 [ 11   7   7   1   1]
 [  1   0   0   0   0]
 [  0   0   0   1   0]]

Embarked Vs Remaining Dv
Accuracy_score: 0.6591760299625468
Confusion Matrix:
 [[ 23   3  23]
 [  0  12  10]
 [ 24  31 141]]
