# 1. Create a 3x3x3 array with random values 

In [1]:
import numpy as np
a = np.random.random((3,3,3))
print(a)

[[[0.99924475 0.98592529 0.91132775]
  [0.64835586 0.89122968 0.0112779 ]
  [0.14953841 0.38988035 0.97026564]]

 [[0.76537127 0.19250931 0.60727861]
  [0.11884854 0.65474569 0.00809352]
  [0.66331221 0.9879219  0.8801573 ]]

 [[0.15759025 0.19837761 0.41000473]
  [0.43039938 0.93400618 0.56179332]
  [0.19113815 0.8082026  0.21041314]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [2]:
import numpy as np
arr1 = np.diag((0,1,2,3,4,0))
arr3 = arr1[:5,1:]
print(arr3)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [3]:
import numpy as np
arr = np.zeros((8,8),dtype = int)

arr[1::2,::2] = 1
arr[::2,1::2] = 1
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [4]:
import numpy as np

arr = np.random.random((5,5))
print("Before Normalization:\n",arr)

arr_max,arr_min = arr.max(),arr.min()

arr = (arr - arr_min)/(arr_max - arr_min)
print("\nAfter Normalization:\n",arr)

Before Normalization:
 [[0.899885   0.90255106 0.54310665 0.60100583 0.83371918]
 [0.69893173 0.26875185 0.37509365 0.90102592 0.78186794]
 [0.90578147 0.42263101 0.47092895 0.8999844  0.36276878]
 [0.7341267  0.08438553 0.38978823 0.48017701 0.08174875]
 [0.6595901  0.03329737 0.66799196 0.21629307 0.63435636]]

After Normalization:
 [[0.99324175 0.99629746 0.58431928 0.65068058 0.91740561]
 [0.76291862 0.26986679 0.39175073 0.99454941 0.85797618]
 [1.         0.4462358  0.50159262 0.99335568 0.37762454]
 [0.80325743 0.05855483 0.40859295 0.5121923  0.05553267]
 [0.7178271  0.         0.72745691 0.20974101 0.68890538]]


# 5.  How to find common values between two arrays?

In [5]:
import numpy as np

arr1 = np.array([1,2,3,4,5,6,7,8,9,0])
arr2 = np.array([1,3,5,7,9,11,13,15,17,19])

arr1.shape = (2,5)
arr2.shape = (2,5)
print(arr1,end="\n\n")
print(arr2,end="\n\n")

print("Common values of above two arrays:\n",np.intersect1d(arr1,arr2))

[[1 2 3 4 5]
 [6 7 8 9 0]]

[[ 1  3  5  7  9]
 [11 13 15 17 19]]

Common values of above two arrays:
 [1 3 5 7 9]


# 6.How to get the dates of yesterday, today and tomorrow?

In [6]:
import numpy as np
today = np.datetime64('today','D')
yesterday = today - np.timedelta64(1,'D')
tomorrow = today + np.timedelta64(1,'D')

print("Today: ",str(today))
print("Yesterday: ",str(yesterday))
print("Tomorrow: ",str(tomorrow))

Today:  2020-07-26
Yesterday:  2020-07-25
Tomorrow:  2020-07-27


# 7. Consider two random array A and B, check if they are equal

In [7]:
import numpy as np

def myfn(a1,a2) :
    if a1.shape != a2.shape :
        return False
    
    a1 = a1.flatten()
    a2 = a2.flatten()
    
    for i,j in zip(a1,a2) :
        if i != j :
            return False
    return True

# arr1 = np.array([1,2,3,4,5,6])
# arr2 = np.array([1,2,3,4,5,6])

arr1 = np.random.random((2,3))
arr2 = np.random.random((2,3))

print("Checking element by element directly:\n",arr1 == arr2)

print("Checking whethar arrays are same or not:",myfn(arr1,arr2))

Checking element by element directly:
 [[False False False]
 [False False False]]
Checking whethar arrays are same or not: False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [8]:
import numpy as np

arr1 = np.random.random((2,3))
# arr1 = np.array([[1,2,3,4,5],[6,7,8,9,0],[11,12,13,14,15]])
print(arr1)

n = arr1.argmax()
m = arr1.shape[1]

arr1[n//m][n%m] = -1

print(arr1)

[[0.51588882 0.2539616  0.76237352]
 [0.87421728 0.88780728 0.97634292]]
[[ 0.51588882  0.2539616   0.76237352]
 [ 0.87421728  0.88780728 -1.        ]]


# 9. How to print all the values of an array?

In [9]:
import numpy as np
arr1 = np.array([[1,2,3],[4,5,6]])
print(arr1)

[[1 2 3]
 [4 5 6]]


# 10.Subtract the mean of each row of a matrix

In [10]:
import numpy as np
arr1 = np.array([[1,2,3],[4,5,6]])
print(arr1)

y = arr1.mean(axis = 1,keepdims = True) # For each row, and it returns column with mean of each row
print(arr1-y)

[[1 2 3]
 [4 5 6]]
[[-1.  0.  1.]
 [-1.  0.  1.]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [11]:
import numpy as np

arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
n = arr1.size
print("Before:",arr1)
indices_list = [1,3,4,2,1,2,3,2,6,7,8,4,0]
# To remove repeated characters use set
indices_list = set(indices_list)
for i in indices_list :
    if i < n :
        arr1[i] += 1
print("After:",arr1)

Before: [ 1  2  3  4  5  6  7  8  9 10]
After: [ 2  3  4  5  6  6  8  9 10 10]


# 12.How to get the diagonal of a dot product?

In [12]:
import numpy as np

arr1 = [[1,2,3,4],[2,3,4,5]]
arr2 = [[1,2],[2,3],[3,4],[4,5]]
print("Dot product:",end="\n")
print(np.dot(arr1,arr2))
arr3 = np.diag(np.dot(arr1,arr2))
print("Diagonal of Dot product:",arr3)

Dot product:
[[30 40]
 [40 54]]
Diagonal of Dot product: [30 54]


# 13.How to find the most frequent value in an array?

In [13]:
import numpy as np
from collections import Counter
import sys

arr1 = np.array([[1,2,3],[1,1,1],[2,3,1]])
temp = dict(Counter(arr1.flatten()))
print("Dictonary of values using counter:",temp)
mx = -1
n = 0
for i,j in temp.items() :
    if mx < j :
        mx = j
        n = i
print("Most Frequent value:",n)

Dictonary of values using counter: {1: 5, 2: 2, 3: 2}
Most Frequent value: 1


# 14.How to get the n largest values of an array

In [14]:
import numpy as np
arr1 = np.array([1,2,3,4,5,1,421,1,0])
idx = (-arr).argsort()[:3] # To get first n max elements we use (-arr) else use arr
print(arr[idx])
# But above approach takes complexity of o(n+klog(k))

# in basic python with o(n) k largest elements can be found
# iterate and find max value and then remove that item from list and continue iteration again for k-1 times

[[[0.76291862 0.26986679 0.39175073 0.99454941 0.85797618]
  [0.99324175 0.99629746 0.58431928 0.65068058 0.91740561]
  [0.7178271  0.         0.72745691 0.20974101 0.68890538]
  [0.80325743 0.05855483 0.40859295 0.5121923  0.05553267]
  [1.         0.4462358  0.50159262 0.99335568 0.37762454]]

 [[0.80325743 0.05855483 0.40859295 0.5121923  0.05553267]
  [0.7178271  0.         0.72745691 0.20974101 0.68890538]
  [0.99324175 0.99629746 0.58431928 0.65068058 0.91740561]
  [1.         0.4462358  0.50159262 0.99335568 0.37762454]
  [0.76291862 0.26986679 0.39175073 0.99454941 0.85797618]]

 [[0.99324175 0.99629746 0.58431928 0.65068058 0.91740561]
  [0.80325743 0.05855483 0.40859295 0.5121923  0.05553267]
  [1.         0.4462358  0.50159262 0.99335568 0.37762454]
  [0.76291862 0.26986679 0.39175073 0.99454941 0.85797618]
  [0.7178271  0.         0.72745691 0.20974101 0.68890538]]]


# 15.How to create a record array from a regular array?

In [15]:
import numpy as np

arr1 = np.array([[1,1,2,3],[2,3,2,3],[3,2,1,4]])
print(arr1)

[[1 1 2 3]
 [2 3 2 3]
 [3 2 1 4]]


In [16]:
data = np.zeros(3,dtype = {'names':('a','b','c','d'),'formats':('i4','i4','i4','i4')})
data['a'] = arr1[:,0]
data['b'] = arr1[:,1]
data['c'] = arr1[:,2]
data['d'] = arr1[:,3]

print(data)

[(1, 1, 2, 3) (2, 3, 2, 3) (3, 2, 1, 4)]
